### ISSUE TITLE
Syntax for complex Formula's

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/GLM.jl#10]
Right now, a Formula specification looks like:

```
:(y ~ x1 + x2 + x3)
```

This is essentially just an enumeration of the columns of the LHS and the RHS. We would like to support more complex Formula's for use with both DataFrame's and DataStream's. The streaming case poses some challenges, but should be soluble with a little bit more work.

There are several issues that need to be addressed. At a minimum, we need:
- Rules for specifying interactions
- Rules for working with functions of columns
- Rules for turning factor objects into numbers
  - Categorical factors
  - Ordered factors

_Interactions_

Harlan has noted before that specifying rules for interactions is non-trivial because `:` has excessively high precedence in Julia. We can't support things like:

```
:(y ~ x1*x3 + x2:x3)
```

because they are not parsed the way that R would parse them.

At present, I believe the solution is that R's `:` is written as `*` and R's `*` is written as `&`. As such, the previous formula becomes:

```
:(y ~ x1&x3 + x2*x3)
```

This is not a bad solution, although I have mixed feelings about `&`. It provides the right intuitions for interactions of dummy variables in which bitwise operations do actually capture the computations being done, but it doesn't provide the right intuition for interactions of continuous variables. Of course, `:` doesn't provide much intuition either, so this may be a moot point.

_Functions of Columns_

I believe that we support things like `:(y ~ log(x1))`, but am not sure. In general, it would be nice to support things like:

```
:(y ~ clamp(x1, x2, x3))
```

This should be possible using the `with` function when we create a `ModelMatrix`.

_Categorical Factors => Numbers_

The representation of factors is Julia's weak point right now. We have a PooledDataArray object that provides a means for storing factors with a small number of levels that is memory-efficient.

But this backend is not equivalent to the concept of a factor. We should be able to treat DataArray's as factors as well. For a categorical factor `f`, what is essential is the ability to replace `f` with a k-column matrix that indicates whether `f[i] == k` for each of the `k` unique values that `f` takes on. We could do this by supporting either `levels` or `unique` for anything that will be treated as a categorical factor.

A major difficulty arises when working with categorical factors in DataStream's:
- If we run `unique` on a minibatch of 25 rows pulled from a 100,000 row data set, many of the `k` levels will not be present.
- This problem is greatly exacerbated when the DataStream is being evaluated in real-time because the data set itself may not contain all of the levels that we expected it to contain.

To deal with this case, I would propose extending the functions we use for converting factors to allow an optional list of unique levels for each factor. If this list is blank, then we call `levels` or `factors`.

_Ordered Factors => Numbers_

We currently have no mechanism for working with ordered factors. In part, this is because our PooledDataArray is not like R's factor: a PooledDataArray dispatches all comparison operators to the contents so that PooledDataArray's of strings use string ordering for comparisons.

To provide something like R's ordered factor, we need to provide:
- A mechanism for overriding the default ordering
- A mechanism for translating entries of an ordered factor into a numeric representation that respects that ordering

A lot of thought needs to go into this still.

**Comment by martinbel** [comment]
[Here](ftp://ftp.cs.ntust.edu.tw/yang/R-BOOK/Venables,%20WN%20and%20Ripley,%20BD(2002)%20Modern%20Applied%20Statistics%20with%20S,%204th%20Ed.pdf) there is a description of how categorical variable coding was supported in S.

**Comment by andreasnoack** [comment]
Further discussion of this should probably be in either `DataFrames` (where formulas live now) or a separate `Formula` package.

**Comment by kleinschmidt** [comment]
This functionality will live in https://github.com/JuliaStats/StatsModels.jl, too
