### ISSUE TITLE
Interval functionality in predict() function?

### ISSUE THREAD

**Issue by Mokubyow** [JuliaStats/GLM.jl#101]
In R the predict function has an interval parameter where you can specify and retrieve a 95% confidence or prediction interval. Is that possible with the predict() function in Julia? If not it would be a good feature add.

**Comment by kleinschmidt** [comment]
It doesn't look like it's currently possible, but I agree it would be nice to have.  As always, pull requests are encouraged, and this should be pretty straightforward to implement if you're interested in taking a crack at it.
