### ISSUE TITLE
ERROR: @~ not defined

### ISSUE THREAD

**Issue by veryluckyxyz** [JuliaStats/GLM.jl#102]
I tried the first example in the README.md but I get error ERROR: @~ not defined

The ones I tried are
data = dataframes.DataFrame(X=[1, 2, 3], Y=[1,0,1])
glm.glm(Y~X, data, glm.Binomial(), glm.ProbitLink())

I tried above commands with Julia v 0.3.0 and GLM 0.4.3

Perhaps I am doing something wrong?

**Comment by simonster** [comment]
You need to call `using DataFrames` to be able to use `~`. Perhaps the README needs an update.

**Comment by veryluckyxyz** [comment]
Thank you!
