### ISSUE TITLE
Error when using correlation with LinearModel

### ISSUE THREAD

**Issue by veryluckyxyz** [JuliaStats/GLM.jl#103]
Julia> cor(model1.model)
`map` has no method matching map(::RcpFun, ::Array{Float64,1})
while loading In[67], in expression starting on line 1

Perhaps I am missing some dependencies that were not added along with GLM package?

**Comment by dmbates** [comment]
Perhaps `RcpFun` was a `Functor` in the `NumericExtensions` package?  It is no longer in the list of one-argument functors
```julia
julia> subtypes(Base.Func{1})
8-element Array{Any,1}:
 Abs2Fun                      
 AbsFun                       
 CentralizedAbs2Fun{T<:Number}
 EqX{T}                       
 ExpFun                       
 IdFun                        
 LogFun                       
 NotEqZero 
```

It is probably easiest to replace the `map(RcpFun,` with `map(inv,`

**Comment by dmbates** [comment]
@veryluckyxyz I wasn't suggesting that you need to make such a change.  I should have indicated that I was suggesting a possible fix.  I won't get to it today so I left the message for other authors who may want to make the change.

**Comment by simonster** [comment]
Sorry, this was my fault. Should be fixed when you run `Pkg.update()`.

**Comment by veryluckyxyz** [comment]
Thank you Simon, Douglas!
