### ISSUE TITLE
Syntax of the weight option

### ISSUE THREAD

**Issue by matthieugomez** [JuliaStats/GLM.jl#106]
All functions in the `StatsBase` package accept weights using the special type `WeightVec`. This syntax consistency among all the functions in StatsBase is really handy.

Similarly, it would be nice if functions in GLM accepted weights as a `WeightVec` objects rather than through an argument called `wts`.  Moreover, the field in GlmResp could be a w::WeightVec rather than wts::V.

**Comment by nalimilan** [comment]
I think one of the reasons why it's been written that way is that `git` takes more arguments than e.g. `std`, which makes it harder to remember the exact order, and to support all possible combinations of optional arguments. Another thing to keep in mind is that it would be nice to be able to specify weights as the name of a column (via a symbol), not only via a `WeightVec`. So you'll have to make sure the types are specific enough to introduce no dispatch ambiguity.

That said, if you move weights to a positional argument right after the distribution family, it might work fine. This would have to be harmonized at the StatsBase.jl level.

(I think I would have preferred all weights to be passed as a keyword argument, but for functions like `mean` it incurs a non-negligible performance hit...)

**Comment by nalimilan** [comment]
See also https://github.com/JuliaStats/GLM.jl/pull/128
