### ISSUE TITLE
How to fit without an intercept?

### ISSUE THREAD

**Issue by cstjean** [JuliaStats/GLM.jl#109]
My reading from [this](https://github.com/JuliaStats/GLM.jl/pull/90#discussion_r16936476) is that it's supported, just not explained.

**Comment by dmbates** [comment]
Much of the documentation assumes that the reader has used R, which, of course, is not a valid assumption.  Anyway, the way to suppress an intercept is to include `0 +` in the formula.  So `y ` 1 + x` fits a model slope and intercept while `y ~ 0 + x` suppresses the intercept.

**Comment by cstjean** [comment]
Thank you.
