### ISSUE TITLE
Negative binomial regression

### ISSUE THREAD

**Issue by ahwillia** [JuliaStats/GLM.jl#121]
I've been doing a little work with negative binomial regressions lately and noticed that they weren't supported by this package yet. Looking through the source code, I'm not 100% certain what I would need  to add to support this functionality. I gather I need to define functions for `canonicallink`, `glmvar`, `mustart`, `devresid`... but I'll admit that I'm not 100% sure what a couple of these refer to.

As a corollary to this, it would be nice to add some comments to `glmtools.jl` so that it is more understandable for an outside observer (like myself!). Or even some documentation that explains the guts, though this would be more involved.

**Comment by nalimilan** [comment]
Sorry for the lack of response. It would be nice to support, but we'd need somebody to be ready to work on it. If you want to give it a try, we can give you some assistance.

**Comment by ahwillia** [comment]
No worries - I will let you know if I find the time to do it. If I'm able to, I'd implement and prototype it in my own repo first and then migrate it over.
