### ISSUE TITLE
Many exported functions no longer exist

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/GLM.jl#125]
I decided to `import GLM` into the `MixedModels` package as a starting point for fitting GLMMs.  In the process I noticed that there were several functions exported from the `GLM` module in `src/GLM.jl` that no longer exist.  I'll clean them up tomorrow and submit a pull request.

**Comment by pkofod** [comment]
Were there functions the ones you removed from export in https://github.com/JuliaStats/GLM.jl/pull/123?

**Comment by andreasnoack** [comment]
I think this is fixed now.
