### ISSUE TITLE
DomainError with LogLink

### ISSUE THREAD

**Issue by michaelstepner** [JuliaStats/GLM.jl#129]
I'm trying to estimate a GLM using **GLM.jl**, running a separate regression on many groups.  But for some of the groups, the program crashes with a DomainError().  The issue appears to be an attempt to take the log of a negative number on line 70 of **glmtools.jl**.

I've posted [a Gist with examples](https://gist.github.com/michaelstepner/ede889ea540048d4105c): one that passes and one that fails.  The gist contains a 5-line script and two 48-row dataframes (CSVs) with very similar data, one of which throws a DomainError() when run through **GLM.jl**.

**Comment by andreasnoack** [comment]
Are you sure that you want to use the `LogLink` link function and not the `LogitLink` function? The latter will give you a logistic regression.

**Comment by dmbates** [comment]
You are using a `LogLink` with a `Binomial` distribution family.  For the binomial the mean parameter is the probability of success which must be in the range (0.0,1.0).  A log link does not guarantee this, which is why `LogitLink` or `ProbitLink` or others that do guarantee this are used.

**Comment by michaelstepner** [comment]
Thanks for the quick responses, Andreas and Dogulas!  I've managed to solve the problem.

I am certain that I want to be using the `LogLink` with my `Binomial` distribution, not a `LogitLink`. The model I am estimating has `log(mortality) = a + b * age` which is a standard Gompertz survival model. I observe the number of deaths & survivals at each age, which has a binomial distribution.  Therefore the correctly specified GLM for the survival model I am estimating has a `Binomial` distribution with a `LogLink`.

You are correct in pointing out that the `LogLink` does not guarantee a positive probability of success.  The model is still well-defined as long as the probability of success is always positive in the region of the true parameter values and estimated parameter values, at the ages I observe.  This is true for all of my data.

The issue I was encountering was that the optimization algorithm's search for optimal parameter values led it to a region with negative probabilities of success.  I fixed this by starting the search at parameter values close to the true values, using the `start()` option.  I've [updated my Gist](https://gist.github.com/michaelstepner/ede889ea540048d4105c) with working example code, in both Julia and R.

May I make a couple suggestions that would assist future users in a similar situation?

* The `start()` option is presently undocumented, and it would be very useful to add it to the docs. In fact, the only reason I found it was by running the model in R, getting it working in R using the `start()` option, and trying whether the Julia package also had a `start()` option on a whim.
* R provides an informative error message in this case: `Error: no valid set of coefficients has been found: please supply starting values`.  It would be helpful if **GLM.jl** had a similarly informative error for this scenario.

**Comment by nalimilan** [comment]
Makes sense. Do you think we would be able to make a pull request to transform the `DomainError` into a more explicit message?

**Comment by pkofod** [comment]
^ +1, and maybe also document the `start`-option.
