### ISSUE TITLE
Change semantics and calling sequence of updatemu!?

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/GLM.jl#132]
Just a heads up that I would like to change the semantics and calling sequence of the `updatemu!` methods.  Alternatively I could split the updating part of 

``` julia
updatemu!{T<:FPVector}(r::GlmResp{T}, linPr::T)
```

into a separate function.

For an `LmResp` this method is trivial.  For a `GlmResp` this method copies `linPr`  into the `eta` member (or adds `linPr` and `offset` into `eta`) then updates `mu` and other vectors.   In the generalized linear mixed models code I would like to build `eta` from various terms in place, then update `mu` and the other vectors.  It would help to have the updating part split out from the copying part of the `updatemu!` methods.

Does anyone have any suggestions for the best approach?  I think the second is preferable except that the name `updatemu!` would then more properly apply to the function called by `updatemu!`.

**Comment by andreasnoack** [comment]
@dmbates What is the status on this?

**Comment by dmbates** [comment]
@andreasnoack No longer relevant.
