### ISSUE TITLE
lm won't take integer as response variable

### ISSUE THREAD

**Issue by xqrongm** [JuliaStats/GLM.jl#134]
lm won't take integer as response variable and float as predictor variable.

**Comment by andreasnoack** [comment]
This is fixed on master. I'll have a new version tagged. Until then, you can do `Pkg.checkout("GLM")`.

Please remember to provide the output from `versioninfo()` and `Pkg.status("GLM")` when submitting a bug report.

**Comment by andreasnoack** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/5000
