### ISSUE TITLE
glmvar(::Binomial, ...) or glmvar(::Bernoulli, ...) seem to be slow

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/GLM.jl#136]
@andreasnoack I see that you added the code to use both `μ` and `η` in the `glmvar` method for the Binomial distribution.  I can agree that it is a good idea to stabilize the calculation of  `μ * (1 - μ)` but this approach turns out to be rather expensive.  I'm doing some timings on Generalized Linear Mixed Models and about 35% of the time to fit such a model is spent in `glmvar` and most of the time it could be evaluated as `μ * (1 - μ)` without any problems.

The evaluation

``` jl
    μ = linkinv(link, ifelse(η < 0, η, -η))
```

is an expensive no-op when `η < 0`, because it is just repeating the calculation that produced  `μ`.

It may make sense to invoke the inverse link only when  `μ` is close to 1, say `μ > 0.999` or whatever threshold seems reasonable.

Also, I think you are being generous in your definition of odd link functions.   `InverseLink` is not odd and I don't think `CauchitLink` is either.

I wanted to run this by you to see if I am on the right track before producing a PR.

**Comment by andreasnoack** [comment]
I couple of fast comments and then I'll write more when I've wrapped my head around this again.

1. I agree that we are spending too much time on evaluating the special functions because some of them are computed more times than necessary. For models with few regressors, it can be a very large fraction of the time that is spent on that right now which is not okay.

2. When I made these changes, I was able to push the limit for where separation will break the algorithm quite a bit. Maybe we just want to stop earlier and say that the data is bad but I hope that we are able to make precise evaluations without a too large speed penalties.

3. As we've discussed earlier, we should consider a fast path for the exponential family because all the terms cancel so it should be possible to get a much faster version without numerical problems in those cases.

4. It might be worth considering a convergence criterion based on the score instead of the change in the log-likelihood. It appears to me that the score and the information are much cheaper than the log-likelihood.

5. I agree that the `InverseLink` is not "odd" but I do think that `CauchitLink` is.

**Comment by StefanKarpinski** [comment]
> It might be worth considering a convergence criterion based on the score instead of the change in the log-likelihood. It appears to me that the score and the information are much cheaper than the log-likelihood.

Could you use a cheaper, less accurate convergence criterion and when it indicates convergence, check the real one? If the cheaper one sometimes fails to indicate, you could check the real one occasionally.

**Comment by dmbates** [comment]
First, I should point out that this is probably not a big deal for glm's because they typically converge in a handful of iterations.  In trying to fit a generalized linear mixed model, however, I do that process hundreds of times and this can be a bottleneck.

@andreasnoack Perhaps we should leverage Julia's excellent multiple dispatch here and perform the whole update dispatching on the distribution and the link.  In my case the bottleneck is the equivalent of the `updatemu!` generic.  In practice there are only a few distributions (Bernoulli, Binomial, Poisson, Gamma) used and almost always with the canonical link.  If we hand-crafted `updatemu!` methods for the combinations (Bernoulli, LogitLink), (Binomial, LogitLink), (Poisson, LogLink), and (Gamma, InverseLink) we could cover the vast majority of cases that are actually used.  We would be able to take advantage of these links being canonical links, which leads to some cancellation, and create loops that are suitable for `@inbounds`, `@simd` and `@threads`.  Right now we don't get as much benefit from the possible optimizations because we are calling generics like `linkinv`, `mueta`, `glmvar`, ...  

I don't know how much specialization goes on in the code generation for specific methods of `updatemu!`.  The `GlmResp` type signature includes the distribution and link but I don't know if that causes the methods for `linkinv` and `glmvar` to be specialized and possibly inlined during compilation.  In any case it would not be difficult to specialize the hell out of the most common cases.

**Comment by dmbates** [comment]
I tried what I suggested and didn't save a whole lot of time.  You can dispatch on the distribution and the link and use code that will stabilize the calculations and avoid reevaluating many function calls but that didn't help my case very much.

By the way, the cancellation of terms occurs when the distribution is in the exponential family and the link is the canonical link.  That's when the derivative of the inverse link (the value of the `mueta` function for the link) is equal to the variance function (`varfunc` for the distribution).

I think in my case the biggest bang might be from using `@threads` in Julia 0.5  It's an ideal operation for multithreading.

**Comment by andreasnoack** [comment]
Do you still see ~35% of the time spent in `glmvar`?

> By the way, the cancellation of terms occurs when the distribution is in the exponential family and the link is the canonical link.

I don't know why I keep writing exponential family when I talk about the cancellation.

> I think in my case the biggest bang might be from using @threads in Julia 0.5 It's an ideal operation for multithreading.

Yes. That will probably be an easy way to get a speedup. Using a vectorized special functions library might also have an effect.

**Comment by dmbates** [comment]
@andreasnoack I no longer see a large fraction of the time being spent in `glmvar`.  It is `updatemu!` as a whole that takes up the majority of the time.  I think my earlier statement about time spent in `glmvar` may have been a result of misreading a profile flame plot.  The new version of those plots from `ProfileView.view` seems to merge the time spent on several lines together as one color.

I may be able to cut down on execution time for fitting a `MixedModels.GeneralizedLinearMixedModel` by choosing smarter starting estimates or by seeing where it is allocating memory.  I will also try using threads in Julia 0.5- but first I will need to rewrite all my `Ax_mul_Bx!` methods :-)

**Comment by dmbates** [comment]
I looked at memory allocation and was surprised to see that most of the allocation takes place in the loop that I thought I had carefully crafted to avoid any allocation.  The `updatemu!` function runs one loop in which a number of calculations on similar vectors are done one index at a time.  I use a slightly different version in MixedModels/src/glm.jl and get this result from a run tracing allocations
```
        - function updateμ!{T<:AbstractFloat, D<:Bernoulli, L<:LogitLink}(m::GeneralizedLinearMixedModel{T,D,L})
        0     y, η, μ, wt, wrkres, wrkwt, dres = m.y, m.η, m.μ, m.wt, m.wrkresid, m.wrkwt, m.devresid
        - 
    16016     if !isempty(m.offset)
    16016         broadcast!(+, η, η, m.offset)
        -     end
    16016     priorwts = !isempty(wt)
        - 
        0     s = zero(T)
107579472     @inbounds for i in eachindex(η)
 30974944         ηi = η[i]
 61949888         ei = exp(-ηi)
 30974944         opei = 1 + ei
 30974944         μi = μ[i] = inv(opei)
 61949888         dμdη = wrkwt[i] = ei / abs2(opei)
 30974944         yi = y[i]
 61949888         wrkres[i] = (yi - μi) / dμdη
 80768688         dres[i] = -2 * (yi == 1 ? log(μi) : log1p(-μi))
        0         if priorwts
 30974944             wti = wt[i]
 61949888             dres[i] *= wti
 61949888             wrkwt[i] *= wti
        -         end
 61949888         s += dres[i]
        -     end
        0     s
        - end
```

The `y`, `wt`, `wrkres`, ... are all `Vector{T}`.  I was hoping that the scalars would just sit in floating point registers.  I don't understand where the memory allocation is coming from.  Would it be an advantage to break the one loop that does so many calculations into two or more loops?

**Comment by simonster** [comment]
Can you give the `@code_warntype` output?

**Comment by dmbates** [comment]
@simonster Thank you for the reminder.  I had been using `DenseVector{T}`, not `Vector{T}` as the type of those vectors in the definition of the GeneralizedLinearMixedModel type.  If I change them to `Vector{T}` things speed up considerably.

**Comment by dmbates** [comment]
By considerably I mean about 2 orders of magnitude on one of my large examples.  Thank you again @simonster .  This community is wonderful.

**Comment by andreasnoack** [comment]
@dmbates There might be room for further optimizations but can the specific issue here be considered fixed?

**Comment by dmbates** [comment]
@andreasnoack yes.
