### ISSUE TITLE
convert GLM models to StatisticalModel

### ISSUE THREAD

**Issue by cjprybol** [JuliaStats/GLM.jl#139]
I was wondering what the relationship between the models output by the GLM package and the StatisticalModel object from StatsBase was, and how to convert between the two. More specifically, I would like to know how to retrieve the R<sup>2</sup> of a fit linear model

For example
```julia
using GLM
using DataFrames, DataArrays
df = DataFrame(X = [1,2,3], Y = [2,4,7])
model = lm(Y ~ X, df)
```

returns an object of type `DataFrames.DataFrameRegressionModel{GLM.LinearModel{GLM.LmResp{Array{Float64,1}},GLM.DensePredQR{Float64}},Float64}`

while `R2, R², adjR2, and adjR²` all accept inputs in the form of `(obj::StatisticalModel, variant::Symbol)`

In StatsBase.jl/src/statmodels.jl I can find that the type RegressionModel is a subtype of StatisticalModel, `abstract RegressionModel <: StatisticalModel`, but is the same true for `DataFrames.DataFrameRegressionModel`?

using the model object above, I've tried converting with `convert(model, StatisticalModel)` and `convert(model, RegressionModel)`, as well as running the `R2` function on the GLM model with `R2(model, :Y)`

Sorry if I'm missing something obvious, but I haven't been able to figure it out from the documentation. Thanks in advance for any help!

**Comment by nalimilan** [comment]
There's no conversion to perform. GLM models are subtypes of the abstract type `StatisticalModel`. We just need to tag a new release with the support for `R²` and `R2`. Or use `Pkg.checkout` to test the development release.

**Comment by nalimilan** [comment]
See https://github.com/JuliaLang/METADATA.jl/pull/5224.

**Comment by nalimilan** [comment]
The new release is available now.

**Comment by cjprybol** [comment]
Thank you @nalimilan! Checking out the `GLM.jl` master branch with `Pkg.checkout` yesterday solved the problem. Just did a `Pkg.update` to get the release and that is working as well.
