### ISSUE TITLE
"predict" method does not keep NA values

### ISSUE THREAD

**Issue by JessicaYK** [JuliaStats/GLM.jl#141]
Hi all,

The data that I use contains variables with some "NA" values. I need to run regressions on them, and I want my prediction to show the positions of variables that have predictions as "NA". However, the "predict" method does not do this. It only shows the vector consisting of non-NA predictions. Is there a way I can show NA predictions? Any help will be appreciated!

**Comment by andreasnoack** [comment]
Can you provide a small example that shows the issue? It will make it much simpler to investigate.

**Comment by JessicaYK** [comment]
@andreasnoack Thanks for your reply!

I am not sure what would be the best way to present an example here. Let's assume that I am running simple regression of Y on X (both Y and X containing 10 values each). However, let's assume Y contains one missing value (NA) in the first position Y[1,1]. When I run regression and predict values from regression, Julia gives me an array consisting of 9 values. However, what I want is an array that consists of 10 predicted values but the first value being NA. 

Is there a way I can do this with the GLM package? Or do I have to write a function myself for this?

**Comment by andreasnoack** [comment]
The best way is to provide a small piece of code that can be copied into the Julia and executed. In that way, it's typically easy to see the problem and propose a solution. In your case, something like
```jl
julia> using DataFrames

julia> df = DataFrame(x = randn(10), y = randn(10));

julia> df[:y][1] = NA;

julia> predict(lm(y~x, df), [ones(10) df[:x]])
10-element Array{Float64,1}:
  0.144802
 -0.13223 
  0.284572
 -0.511882
  0.11762 
  0.190414
 -0.553935
  0.048628
 -0.01136 
  0.548038
```
might have shown what you were asking about.

I don't really see how you can predict that the `y` element is `NA`. The prediction is a function of the `x`s and the parameters. It sounds as if your `x` doesn't have `NA`s and then either none or all of the elements in `y` would be `NA` depending on whether there are `NA`s in the regression coeffients or not.

**Comment by JessicaYK** [comment]
@andreasnoack Thank you for a quick response!

I see! I am pretty new to the thread so wasn't sure about how to present questions nicely. Thank you for the suggestion!

Actually, glm ignores NA values, so if there are missing values in the Y, then prediction ignores them. However, looking at your example, I think "[ones(10) df[:x]]" does the trick that enables me to show prediction even for the missing outcome. It will be great if you can explain what it does exactly! Does that fill ones to the Y value?

Also, what if there is a NA value in X? Can I make the prediction show the NA value?

Thank you for your helpful comments!

**Comment by andreasnoack** [comment]
You are welcome and no problem that you are not sure about the format in here. We have all been new to it at some point. For a question like this one, it is actually more appropriate to post on https://groups.google.com/forum/#!forum/julia-stats whereas this place is mainly for bugs or design discussions related to `GLM.jl` more than questions about use. However, since we have started the conversation here, let's just finish it here.

In `lm` the `predict` function is fairly simple and is just computing `X*β̂`, i.e.
```jl
julia> prVals = [ones(10) df[:x]]
10x2 Array{Float64,2}:
 1.0  -0.208228 
 1.0  -0.0711758
 1.0   0.698314 
 1.0  -0.0662767
 1.0   0.834966 
 1.0  -1.22193  
 1.0   1.35638  
 1.0   1.0735   
 1.0   1.51421  
 1.0  -0.45499  

julia> predict(ft, prVals)
10-element Array{Float64,1}:
 -0.0143628
 -0.0953182
 -0.549847 
 -0.0982121
 -0.630566 
  0.584419 
 -0.93856  
 -0.771464 
 -1.03179  
  0.131397 

julia> prVals*coef(ft)
10-element Array{Float64,1}:
 -0.0143628
 -0.0953182
 -0.549847 
 -0.0982121
 -0.630566 
  0.584419 
 -0.93856  
 -0.771464 
 -1.03179  
  0.131397 
```
so the only way the the `NA` in `y` could affect the predicted values would be through `coef(ft)`. When `NA` are removed, as we do now, then `coef(ft)` doesn't have any `NA`s. If `NA` observations were not removed from the model then all of `coef(ft)` would be `NA`s and all the predicted values would be `NA`s as well.

An `NA` in the values used for prediction would cause an `NA` in the predicted values, i.e.
```jl
julia> ft = glm(y~x, df, Normal(), IdentityLink())
DataFrames.DataFrameRegressionModel{GLM.GeneralizedLinearModel{GLM.GlmResp{Array{Float64,1},Distributions.Normal{Float64},GLM.IdentityLink},GLM.DensePredChol{Float64,Base.LinAlg.Cholesky{Float64,Array{Float64,2}}}},Float64}

Formula: y ~ 1 + x

Coefficients:
              Estimate Std.Error   z value Pr(>|z|)
(Intercept)  -0.137361  0.394318 -0.348351   0.7276
x            -0.590689  0.413625  -1.42808   0.1533


julia> prVal = DataArray([ones(2) randn(2)]);

julia> prVal[1,2] = NA;

julia> predict(ft, prVal)
2-element Array{Union{DataArrays.NAtype,Float64},1}:
   NA    
 -0.17572
```
Notice that I used `glm` here. For some reason this doesn't work for `lm` which is a bug.

**Comment by JessicaYK** [comment]
@andreasnoack This is a really really great answer! Thank you so much! And yes, I will post on the google group from now on.
