### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/GLM.jl#144]
Now that the `dmb/Hermitian` branch has been merged we should tag a new release so that other packages on v0.5-dev are not held up.  Given my history with git it seems best if someone else did the tagging and releasing.

**Comment by andreasnoack** [comment]
`DataArrays.jl` is broken by https://github.com/JuliaLang/julia/pull/16260 on master so maybe we should wait until it has been fixed. We could put it on the agenda for the Saturday hackathon.

**Comment by dmbates** [comment]
@andreasnoack The master branch passed tests on 

```julia
julia> versioninfo()
Julia Version 0.5.0-dev+4811
Commit e261293* (2016-06-16 14:40 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)
```

**Comment by andreasnoack** [comment]
Done
