### ISSUE TITLE
Tag a version and bump REQUIRE to julia 0.5?

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/GLM.jl#151]
I would like to update PR #145 for julia version 0.5.  For that I think I should tag a release and bump the `REQUIRES` to julia 0.5. I think what I do is

``` jl
Pkg.tag("GLM")
Pkg.publish("GLM")
```

then create a branch named julia-0.4 on github

After that I create a new branch on which to make my changes, checkout that branch, modify `REQUIRE`, commit and push the changes then create a pull request.

Have I missed anything here?

**Comment by andreasnoack** [comment]
Can you remind me, why is necessary for #145 to drop 0.4 support?

**Comment by dmbates** [comment]
@andreasnoack One of the purposes of #145 is to allow for multithreading in the evaluation of the working residuals, working weights, etc. for the canonical link.  I just thought it would be cleaner to push all the changes to the v0.5.  If it seems desirable I can backport the methods without back to a julia-0.4 branch once I get them settle on julia-0.5

**Comment by ararslan** [comment]
If we're discontinuing 0.4 support, the branch isn't necessary since folks who want 0.4 support can just check out an earlier tag.

Regarding tagging the version, on Julia 0.5 you'll need the PkgDev package. Then once the appropriate changes have been made on master, you can do
```julia
Pkg.update()
using PkgDev
Pkg.checkout("GLM", "master")
PkgDev.tag("GLM", :minor) # need to bump the minor version if dropping a Julia version
PkgDev.publish()
```

Does 0.4 not support multithreading?

**Comment by dmbates** [comment]
@ararslan I believe multithreading was introduced in 0.5.  It is still a bit risky to use it but the uses here are striaghtforward loops.

**Comment by andreasnoack** [comment]
Fixed
