### ISSUE TITLE
Package fails tests on Julia 0.4

### ISSUE THREAD

**Issue by tkelman** [JuliaStats/GLM.jl#159]
Since the 0.6.0 tag was 0.5-only, the package is still failing on Julia 0.4. http://pkg.julialang.org/detail/GLM.html

Can you backport just the bugfix to a new branch and make a final 0.5.6 package tag?

edit: Another option would be to upper-bound the past tags to StatsBase < 0.11 on both this and MixedModels. Then StatsBase would get held back on 0.4 as long as either of those packages are installed.

**Comment by ararslan** [comment]
Since StatsBase still supports Julia 0.4, I'd probably prefer the former option. That way the version isn't held back unnecessarily on 0.4.

**Comment by dmbates** [comment]
I would very much like to get version 0.6.0 out but am hopelessly confused as to what is needed to be done.  If someone could sketch out what needs to be done I could go ahead and try to get it done.

**Comment by tkelman** [comment]
@simonbyrne tagged it https://github.com/JuliaLang/METADATA.jl/pull/6729 - but since it was Julia 0.5-only, on Julia 0.4 users are still on version 0.5.something of GLM.jl, which is currently failing its tests with the latest version of StatsBase. So I think what should be done is:

- take the most recent commit of GLM.jl that still supported Julia 0.4, and create a new `release-0.5` branch starting from there
- find the commits that fixed the test failure due to latest StatsBase and backport them to this new `release-0.5` branch in a way that still works and passes tests on Julia 0.4
- tag a (hopefully) last 0.5.x version of GLM.jl from that branch

**Comment by ararslan** [comment]
@dmbates If it's easier for you I can do what Tony is suggesting. I've had to do that for other packages so I have some (admittedly limited) experience with that process.

**Comment by tkelman** [comment]
Or we can do the bounds thing. Whatever's easiest for everyone.

**Comment by dmbates** [comment]
@ararslan I would appreciate it if you could do what Tony is suggesting.

**Comment by ararslan** [comment]
Can do 👍
