### ISSUE TITLE
Exception for failure to converge?

### ISSUE THREAD

**Issue by grero** [JuliaStats/GLM.jl#163]
I recently encountered a situation in which I'm doing a sliding GLM fit, i.e. fitting a GLM model to e.g. 10 bins of data in 1 bin overlaps over a total of 100 bins. In this particular situation, I wanted to skip windows that could not be fit, either because of non-positive definite covariance matrix or because of failure to converge. Thus, in my loop I ended up with code like this

```julia
for w in windows
 try
   fit(GeneralizedLinearModel, X, y, args...)
catch ee
  if isa(ee, Base.LinAlg.LAPACKException) || isa(ee, Base.LinAlg.PosDefException)
   continue
 else
  rethrow(ee)
 end
end
```
However, with this construct, I am not able to test for 'failure to converge' errors. I added this little bit to GLM

```julia
type FailureToConvergeException <: Exception
   msg::String
end
```
and changed line 242 of glmfit.jl  to 

`julia cvg || throw(FailureToConvergeException("failure to converge in $maxIteriterations"))`.

This allows me test for FailureToConvergeException in my try...catch . 
I'm not sure if this is something people would be interested in, in which case I'm happy to create a pull request.

**Comment by ararslan** [comment]
You could check using `isa(ee, ErrorException)`; that's the type of exception thrown by `error`. However, the check at line 225 could also trigger that, so it's not a great proxy. Something like what you propose sounds good to me, though I think the name could be simplified to `ConvergenceException`. If you wanted to go crazy with it, you could do something like
```julia
type ConvergenceException <: Exception
    iters::Int
end
Base.showerror(io::IO, ce::ConvergenceException) =
    print(io, "failure to converge after $(ce.iters) iterations")
```

**Comment by grero** [comment]
Yeah that is a better name : ) It seems that this is useful outside of GLM, though. Is there a better package against which to make a pull request? StatsBase, maybe?

**Comment by nalimilan** [comment]
Makes sense. Add it to StatsModels rather, since that's where this kind of functions are going to live in the future.

**Comment by kleinschmidt** [comment]
It might actually make more sense to put that in `StatsBase` for now, since the modeling stuff from there hasn't been migrated to `StatsModels`.  Having it all in one place will make that migration process easier.

**Comment by ararslan** [comment]
@grero Would you be willing to submit a PR for this functionality in StatsBase then?

**Comment by grero** [comment]
Sure, just created pull request for this over at StatsBase

**Comment by ararslan** [comment]
Great, thanks! I'll close the issue here then.

**Comment by ararslan** [comment]
Actually no, sorry, this should be kept open so we know to use this error once it's added to StatsBase!

**Comment by ararslan** [comment]
Okay, now that https://github.com/JuliaStats/StatsBase.jl/pull/225 has been merged, these are the next steps:
- [ ] Tag a new release of StatsBase
- [ ] Bump the minimum StatsBase requirement of GLM to the new version
- [ ] Use `StatsBase.ConvergenceException` here in GLM
- [ ] Profit!
