### ISSUE TITLE
unclear how to use newx in predict

### ISSUE THREAD

**Issue by mkborregaard** [JuliaStats/GLM.jl#165]
It is hard to use the predict function with new x values.

Consider
```julia
using DataFrames, GLM
x = randn(100); y = x + 0.8 * x
df = DataFrames(x = x, y = y)
mod = lm(y ~ x, df)

# you can get predicted values with
predict(mod)

#then you would assume that you can get predicted values for new x values by
predict(mod, df[:x]) #or
predict(mod, x, df) # or at the very least
x = collect(df[:x]); predict(mod, x)

# but as far as I can see you need
x = collect(df[:x])
newx = hcat(ones(length(x)),x)
predict(mod, x)
```
which isn't really so intuitive. Is there a smarter way of doing this?

**Comment by kleinschmidt** [comment]
The way to do this is

```julia
predict(mod, df)
```

`mod` is a `DataFrameRegressionModel`, which holds onto the formula that it was generated from.  This might not seem so useful in the one predictor case here, but when you have many predictors it would be tedious to list them all in `predict` (or to construct the model matrix manually).

**Comment by kleinschmidt** [comment]
(This could be better documented, though. Although the functionality for this is moving to StatsModels so it makes more sense to document it there, and point people to that for fitting GLMs with data frames/tabular data and formulas)

**Comment by mkborregaard** [comment]
Oh nice, thanks a lot! Is anyone currently working on https://github.com/JuliaStats/GLM.jl/issues/101? It would be very useful, but perhaps not so straightforward for GLMs with the link function.

**Comment by kleinschmidt** [comment]
Not to my knowledge, and it's a little out of my depth. But I agree it would be nice to have.

**Comment by mkborregaard** [comment]
Very nice to have - I could do a PR just for the `lm` case but I guess you need the interface to be consistent across glm and lm.

**Comment by kleinschmidt** [comment]
That would be a good start, nevertheless, and it should be possible to do it such that the interface would be consistent.
