### ISSUE TITLE
lm and glm should accept an additional "test" parameter different from zero.

### ISSUE THREAD

**Issue by skanskan** [JuliaStats/GLM.jl#180]
It would be nice if lm and glm also accepted a test parameter other than zero in order to calculate the p-values.
Otherwise you need compute it manually and that could be wrongly done or change the data and that could violate some assumptions.

For example is quite common to test if the the coefficient "b" is 1.
Y = a+b·X

**Comment by dmbates** [comment]
That can be accomplished by using an offset in the model.

**Comment by skanskan** [comment]
Maybe is not the same in general.

From the help
'An offset is a term to be added to a linear predictor, such as in a generalised linear model, with known coefficient 1 rather than an estimated coefficient'

But I don't want to fix that coefficient, I want to estimate it, but in order to test its significance I want to test it against 1 instead zero.
