### ISSUE TITLE
Implement ANOVAs for lms

### ISSUE THREAD

**Issue by LewisHein** [JuliaStats/GLM.jl#181]
This is an attempt to revive #70 and resolve the issues around it. The purpose of this issue is to decide exactly how we should resolve some people's reservations about the original implementation.

If I understand the preceeding in issue #65 and PR #70 discussion correctly, ANOVA tables are objectionable because they give false impressions, and we want a truly general way of comparing two models, null and alternative based on their F statistics. I have a couple issues with this previous discussion.

1) @dmbates Your comments opened my eyes to a new way of thinking about ANOVA models. I think it would be great if Julia could finally have an implementation of ANOVAs that is general and done right, but let's not lose perspective. There truly is a place in this world for the default alternative hypothesis of "The response differs in at least one possible case", because that's the one we want 99.9% of the time.

1) I feel like the discussion went down a rabbit hole, big-time. As mentioned above, It was a fascinating, useful, and productive rabbit hole, but I don't think rabbits are our highest priority right now. Again, as above, it would be great to make Julia have a general, well-done implementation of ANOVA, BUT, and this is a really big BUT, we've got to have the simple interface that everyone is used to thinking about. We can call the shots to some extent for how people do things in Julia, but the way people are used to thinking about ANOVA (as a test of a null hypthothesis that the response variable is the same across all possible values of predictors) isn't going to go away anytime soon. It is perfectly correct, as far as it goes, but not very general. My fear is that if we take users coming from this paradigm and suddenly drop them into the fully general case, they won't know how to formulate the special case they are used to. A few will push ahead and figure it out, but many will throw up their hands in frustration and walk back to R or SPSS. This would be a shame.

@dmbates You and most of the other people who write GLM.jl are statisticians and know statistical theory inside and out. I am not. I am a mathematically-minded scientist who is more stubborn about trying to figure things out than some others I know. You guys, with your intimate knowledge of stats theory, are making GLM.jl one of the best stats packages out there. But again, none of us represent the majority of the intended end users. These include many people who just had a few stats classes for their degrees and were never taught these details we are discussing. If we don't give them a familiar interface, we will scare them away, and be left with only professional statisticians and extra-stubborn scientists in our user base. Everyone else will go back to R and Julia won't have conquered the world.

In summary, the above is my long-winded argument for why we should not jump straight into full generality of ANOVA as a comparison between two models. My suggestion instead is to include this general feature, but include a smaller, less general version `ANOVA(mod::RegressionModel)` to keep less theoretical-minded people happy.

If I understand the discussion correctly (which I quite possibly don't), we could even go so far as to have
```{.jl}
    function anova(nullmod::RegressionModel, altmod::RegressionModel=lm(nullmod.rr~1))
        #anova stuff
    end
```

I haven't worked this out properly, but it seems that this default would just enable people to use
```
    mod = lm(@formula(pred~resp))
    anova(mod)
    #Results appear
```
as they are used to, without thinking too much about altmod. The more advanced users can go ahead and use whatever alternative model they please.

Note: As above, I have not worked out all the statistics in these above examples, and I do NOT claim that they are error-free. They are there for illustration of what I am thinking about.

**Comment by LewisHein** [comment]
As a further incentive, 85% of respondents to my poll over at the Julia discourse have said they could use ANOVA in GLM.jl. With all due caveats about voluntary response sampling and small sample sizes, I think this is just another reason to get it done, and done right.

**Comment by andreasnoack** [comment]
Personally, I mainly miss a handy function for computing the LR test statistic and p-value for a test between two nested models either just by supplying the two models or a model with some kind of specification of (linear) restrictions on the coefficients. Is it useful to carry around all the ANOVA baggage?

**Comment by LewisHein** [comment]
@andreasnoack I miss this test too. This is the main reason that I want to get it in here, but maybe ANOVA baggage is not necessary.

However, many times that I do this test, the variables are indicator variables for categories, and the null model is simply response~1. Given that this common special case has a special name (ANOVA) it seems logical to at least give a nod to that.

After thinking it over, I see another option. Add a function `ftest(mod1::RegressionModel, mod2::RegressionModel)` and write documentation that clearly spells out how to do an ANOVA with the `ftest` function. As a bonus, we will then avoid having a function named `anova` that computes ANOVAs, but also computes other things that aren't ANOVAs.

**Comment by nalimilan** [comment]
> After thinking it over, I see another option. Add a function ftest(mod1::RegressionModel, mod2::RegressionModel) and write documentation that clearly spells out how to do an ANOVA with the ftest function. As a bonus, we will then avoid having a function named anova that computes ANOVAs, but also computes other things that aren't ANOVAs.

At least it doesn't seem anybody objects to adding such a function, so I guess you could start with that. Though I think it should be more general and accept more than two models, returning a table like R's `anova` (cf. [my comment](https://github.com/JuliaStats/GLM.jl/pull/70#issuecomment-302018488) on the other issue).

**Comment by LewisHein** [comment]
Excellent. I now have a place to start while we continue discussing this

I think it bears repeating, though, that our intended user base should ultimately call the shots if we want to attract them and keep them around. I am all for doing this right according to statistical theory, but within the constraints of making a comprehensible interface. 

I do not claim to know which way said intended user base would call this shot, but I have a gut feeling that we'd better not make it too hard when they think "I want to do an ANOVA. Can I do that with Julia?" If we make it too hard, they'll just go back to R

**Comment by LewisHein** [comment]
@nalimilan I am a little confused by your suggestion. I see a unique, logical way to compare two models to each other, but there are O(n!) ways to do pairwise comparisons between n models. Which of these ways are we to choose in the general n-model comparison and why?

**Comment by nalimilan** [comment]
Closing since https://github.com/JuliaStats/GLM.jl/pull/182 has been merged.
