### ISSUE TITLE
Handling rank deficiency in the model matrix

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/GLM.jl#200]
It is reasonably easy now to detect rank deficiency in the model matrix, `X`.  In the MixedModels package I have added code like
```julia
    T = eltype(X)
    cf = cholfact!(Symmetric(X'X, :U), Val{true}, tol = -one(T))
    r = cf.rank
    n, p = size(X)
    if r < p
        inds = sort!(cf.piv[1:r])
        X = X[:, inds]
    end
```
but that just drops the columns that result in the rank deficiency.

There are several things that could be done for the coefficients etc.  The R approach is to define them to be missing.  We emulated that in https://www.jstatsoft.org/index.php/jss/article/view/v052i05/v52i05.pdf

Other systems define the coefficients for the rank deficient columns to be zero, which, I think, corresponds to the minimum length solution for the underdetermined least squares problem.  That still doesn't solve what to do about standard errors, etc.

I am willing to write the code to handle rank deficiency but first I wanted to check if there are opinions on what to do when it occurs.

**Comment by nalimilan** [comment]
I find the R approach of showing estimated coefficients as `NA` (or probably `NaN` in Julia) useful, as you can see what coefficients were dropped by looking at the model table. So if we can replicate that, I'm all for it.

**Comment by ararslan** [comment]
I also like the idea of using `NaN` in Julia, provided we emit an informative warning in the case of rank deficiency. Since `NaN` is poisonous, unless we actively filter out `NaN`s in the computations, coefficients for any given column could actually be `NaN`, right?

**Comment by dmbates** [comment]
Having thought about this a bit more, I think that it would be appropriate to return zero, or perhaps -0.0, in the positions of the coefficient vector corresponding to linearly dependent columns of X.

My reasoning is that the fitted values and the residuals are the well-defined quantities in a rank-deficient linear model, because they correspond to projections of the response onto orthogonal subspaces of the sample space.  Assume we use a pivoted Cholesky or QR decomposition to determine the rank, `r`, and that we solve for coefficients using the leading r by r block of the triangular factor.   We get a length r coefficient vector in the permuted order.  If we expand this with zeros to length p, the number of columns in X, and apply the inverse permutation, we have a β that gives the desired Xβ.  There is an entire linear subspace of values of β that give the desired Xβ but this one happens to be easy to evaluate.

I would suggest actually using `-zero(T)` in these positions so that zeros induced by rank deficiency can be distinguished from incidental zeros.

I think it would be appropriate to use NaN for the standard errors of these coefficients.  The `vcov` result, which is used to evaluate the `stderr` result, is undefined in general but becomes well-defined if we drop the trailing (in the permuted order) coefficients.

This is the approach I am taking in the `ZeroCol` branch of the `MixedModels` package and I hope it makes sense.

**Comment by nalimilan** [comment]
Disregarding mathematical reasons to use `0.0`, I think `NaN` would be more obvious to distinguish a coefficient for a predictor which has been dropped from a coefficient which happens to be `0.0`. Using `-0.0` for that doesn't sound like it would be clearer as that's quite a weird quantity. As @ararslan noted, `NaN` also has the advantage of poisoning any further computations, which can help catching bugs.

**Comment by dmbates** [comment]
@nalimilan Well my point was that I want Xβ to be the correct projection.  The coefficients that we solve for are only correct, in the sense of creating the correct prediction, if the others are all zero.  If the others are `NaN` then Xβ will be a vector of `NaN`s

**Comment by nalimilan** [comment]
I see your point. But is that property useful in practice? It's not that hard to replace `NaN` with `0` when you know what you're doing.

**Comment by dmbates** [comment]
I do advocate defining the standard errors and any correlations involving the linearly dependent coefficients as `NaN` so it is easy to spot them in a coefficient table.

**Comment by nalimilan** [comment]
Well, I'm fine with whatever solution you prefer.

**Comment by Nosferican** [comment]
Why not drop the linearly dependent coefficients and emit a message? Keeping the linearly dependent predictors might affect the behavior of other functions (e.g., `dof`, `dof_residual`, Wald tests, etc.)

**Comment by nalimilan** [comment]
> Why not drop the linearly dependent coefficients and emit a message? Keeping the linearly dependent predictors might affect the behavior of other functions (e.g., dof, dof_residual, Wald tests, etc.)

I find it more useful to keep the coefficients so that you can see which ones could not be estimated from the fitted model itself. It's generally discouraged to use warnings in Julia, and in the present case you can't store a warning to remember which variables were omitted.

**Comment by ararslan** [comment]
> It's generally discouraged to use warnings in Julia

It is?

**Comment by nalimilan** [comment]
I think so. Do you have many examples of functions which print warnings in Base? In general, the idea is that warnings are annoying and should not occur in normal operation. So you need a way to silence them, e.g. via an argument, at which point you can as well throw an actual error by default. That way you can be sure the warning isn't missed.

**Comment by Nosferican** [comment]
What about implementing
```
lineardependent(model)
```
and modifying `coeftable` to have a `@printf` line before returning the result with that information?

**Comment by dmbates** [comment]
I have been experimenting with using a pivoted Cholesky factorization of `X'X` for linear models and can make it work.

It seems that it would be possible to switch all Cholesky-based models (the default solver) to pivoted Cholesky or to keep the current, unpivoted Cholesky as the default and use pivoting and rank detection only with an optional argument.  I think I will adopt the second approach and call the argument `allowrankdeficient` as that should be clearer than `pivot` or `pivoted`.

**Comment by dmbates** [comment]
This is in the `rankdeficient` branch.
