### ISSUE TITLE
UndefVarError: @formula not defined

### ISSUE THREAD

**Issue by dmsorokin** [JuliaStats/GLM.jl#202]
Hello. I've recently updated all packages in my Julia 0.6.1 (then restarted Julia), and now GLM seems to be not working. Same thing happened on my laptop as well. Below is an example from the GLM.jl readme. Probably something has changed in the dependencies? 
![2017-11-28_11-46-25](https://user-images.githubusercontent.com/28688685/33332370-1cc14574-d432-11e7-872d-6ab6c18e273a.png)

**Comment by dmbates** [comment]
This is a result of the changes in `DataFrames 0.11.0` and is being addressed in #201

**Comment by dmsorokin** [comment]
Thank you, I apologize for duplicating the issue. I tried to google the error but couldn't find anything.

**Comment by dmbates** [comment]
No problem.  The connection to the other issue was pretty obscure.
