### ISSUE TITLE
World age error when running a basic example using GLM

### ISSUE THREAD

**Issue by IljaK91** [JuliaStats/GLM.jl#204]
A friend of mine has the following problem with a simple example using GLM:
```
using DataFrames, GLM

X=collect(0.1:0.2:1.1)
Y=collect(0.1:0.2:1.1)

data=DataFrame()
data[:X]=X
data[:Y]=Y

model_test = fit(LinearModel, @formula(Y ~ X),data)
```

This throws the following error:
```
ERROR: MethodError: no method matching @formula(::Expr)
The applicable method may be too new: running in world age 21842, while current world is 24127.
Closest candidates are:
  @formula(::ANY) at C:\Users\Julia_User\.julia\v0.6\DataFrames\src\statsmodels\formula.jl:20 (method too new to be called from this world context.) 
```

Does anybody know what this is about? I remember that I had the same problem some time ago, but after some tinkering the problem solved itself somehow. I am using Atom/Juno and my friend is using EMACS, if that plays a role. We are both on Julia 0.6.1 and use the most up-to-date version of GLM.

**Comment by nalimilan** [comment]
Looks like the versions of GLM, DataFrames and StatsModels are not in sync. If you are indeed using the latest GLM version, the DataFrames version you have is too old, as it's not supposed to export `@formula` at all now. Can you check what versions you are using?

**Comment by IljaK91** [comment]
DataFrames: 0.10.1
GLM: 0.8.1
StatsModels: 0.0.2, which we had to install now.

Other Stats packages:
StatsBase: 0.5.0
StatsFuns: 0.2.0

The same code works in the REPL.

**Comment by IljaK91** [comment]
It seems to work now in Atom/Juno, but the error remains using EMACS/ESS. The issue can be closed.

**Comment by nalimilan** [comment]
OK, cool. You don't actually need StatsModels as long as you're using DataFrames 0.10.1, and things are supposed to work. Maybe related to package caches? You could try to remove the files for GLM and DataFrames under `C:\Users\Julia_User\.julia\v0.6\lib`.
