### ISSUE TITLE
allow arbitrary transformation in @formula

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaStats/GLM.jl#208]
to fit a model i need to specify `@formula(target~a+b)` but i cant do `@formula(fn(target)~fn1(a) + fn2(b))` like I can in R.

would be a great addition. Support for R style literal computation `I(a*b)` would be nice too!

**Comment by nalimilan** [comment]
`@formula` lives in StatsModels. See https://github.com/JuliaStats/StatsModels.jl/issues/25.
