### ISSUE TITLE
Logistic regression fails when Y is CategoricalArrays.CategoricalValue

### ISSUE THREAD

**Issue by ValdarT** [JuliaStats/GLM.jl#218]
Seems that using CategoricalArrays break `glm()` when used as the response variable.

```
using RDatasets: dataset
using DataFrames, GLM

cars = dataset("datasets", "mtcars")
fmla = @formula(AM ~ Cyl + HP)
glm(fmla, cars, Binomial()) # works fine

categorical!(cars, :AM);
glm(fmla, cars, Binomial()) # errors
ERROR: MethodError: no method matching zero(::Type{CategoricalArrays.CategoricalValue{Int64,UInt32}})

fmla2 = @formula(MPG ~ Cyl + HP + AM)
glm(fmla2, cars, Normal()) # works fine
```

**Comment by ValdarT** [comment]
> What was the actual use case when you encountered this?

I was just testing things out. I think people would expect it to work because CategoricalArrays work in other places in the Formula and this is the default type imported by CSV.jl, for example. Equivalent code also works in R.

**Comment by nalimilan** [comment]
> I think people would expect it to work because CategoricalArrays work in other places in the Formula and this is the default type imported by CSV.jl, for example.

It's not the default type for numbers though. So I'm not sure how you would typically end up with a categorical array of `0` and `1` values.

**Comment by ValdarT** [comment]
Using integer codes for categories is quite typical in (enterprise) databases - a big win when you need to move around large amounts of data. 
(It is of course easy to convert to string but seems inconsistent/unexpected to me.)

**Comment by nalimilan** [comment]
What I'm saying is that columns which contain only digits in CSV files are converted to `Vector{Int}`, not to `CategoricalVector{Int}`. So you should never end up with a `CategoricalArray` with only `0` and `1` values by default.

**Comment by nalimilan** [comment]
That said, I don't see a strong reason not to implement `float(::CategoricalArray)` given that `convert` works.

**Comment by dmbates** [comment]
In https://github.com/JuliaStats/StatsModels.jl/pull/28 I suggested adding `model_response` methods to handle combinations of the distribution and vector type.  That may be overly general in that by far the most common case is converting a two-level categorical vector to 0/1 encoding,  However, allowing for greater flexibility when designing the capability may be a good idea.

**Comment by nalimilan** [comment]
Right, I had forgotten that PR. I agree it would be a good move.

https://github.com/JuliaData/CategoricalArrays.jl/pull/133 implements `float(::CategoricalArray)`, which should fix the most immediate problem in the meantime.
