### ISSUE TITLE
Summary and others methods

### ISSUE THREAD

**Issue by lucasfreitas1988** [JuliaStats/GLM.jl#220]
Hello,

Does the glm function of the GLM package not show the summary when it is called?

Example:
```julia
data = DataFrame(X=[1,2,3], Y=[2,4,7])
OLS = glm(@formula(Y ~ X), data, Normal(), IdentityLink())
```                
`summary(OLS)` returns
 ```
DataFrames.DataFrameRegressionModel{GLM.GeneralizedLinearModel{GLM.GlmResp{Array{Float64,1},Distributions.Bernoulli{Float64},GLM.LogitLink},GLM.DensePredChol{Float64,Base.LinAlg.Cholesky{Float64,Array{Float64,2}}}},Array{Float64,2}}
```

I know it sounds like a simple question, but I can not see the summary when I use the `glm` function. I use Atom and Julia 0.6.2.

Actually, I can not see any method directly.

Thank you!

**Comment by andreasnoack** [comment]
Please always provide complete examples that can be copied directly into Julia and run without modifications.
