### ISSUE TITLE
constant slope coefficient model

### ISSUE THREAD

**Issue by atteson** [JuliaStats/GLM.jl#221]
I have a linear model with a single coefficient and I believe the coefficient is exactly equal to 1.  I'd like to test this and see that there is an f-test for nested linear models but couldn't work out how to define a model that has a constant slope coefficient of 1.

I'd also suggest expanding the documentation.  There seems to be a lot of functionality here which isn't documented.

**Comment by nalimilan** [comment]
Please use [the Discourse forum](http://discourse.julialang.org/) for questions, and keep GitHub for bug reports. Thanks!

We are well aware documentation is lacking, but unless you can do it I'm afraid suggestions won't be enough.
