### ISSUE TITLE
GeneralizedLinearModel with QR

### ISSUE THREAD

**Issue by Nosferican** [JuliaStats/GLM.jl#223]
It seems like GeneralizedLinearModels currently only supports Cholesky decomposition. The algorithm to fit GLM with QR in an efficient manner uses something like this,
```
for idx ∈ eachindex(μ, μ′, σ², η)
    @inbounds μ[idx], μ′[idx], σ²[idx] = μμ′σ²(link, η[idx])
end
z  = η + (b - μ) ./ μ′
w  = μ′.^2 ./ σ²
x₀ = x
valid = w .≥ sqrt(eps())
C  = cholfact!(Hermitian(transpose(Q[valid,:]) * Diagonal(w[valid]) * Q[valid,:])).factors
x  = LowerTriangular(transpose(C)) \ (transpose(Q[valid,:]) * Diagonal(w[valid]) * z[valid])
x  = UpperTriangular(C) \ x
mul!(η, Q, x)
...
```
after convergence,
```
x = A \ η
```

**Comment by andreasnoack** [comment]
What is the issue here? If something is failing please provide an example. Otherwise, please expand the explanation.

**Comment by hung-q-ngo** [comment]
Related question: Cholesky and QR are two of the common choices but the solver is still IRLS. In some cases, other solvers (based on L-BFGS, or straight up batch/stochastic gradient descent) are more desirable (e.g. when there is a large number of predictors). Is this worth a separate open issue?
