### ISSUE TITLE
Polynomial terms

### ISSUE THREAD

**Issue by cstjean** [JuliaStats/GLM.jl#225]
This would be nice:
```julia
df = DataFrame(x=1:10, y=(1:10).^2+2)
fit(LinearModel, @formula(y~x+x^2), df)
```
Currently, it returns `no method matching start(::Expr)`. If I replace `x^2` by `x*x`, I get a `Base.LinAlg.PosDefException(3)`

**Comment by andreasnoack** [comment]
Please file this at `StatsModels`
