### ISSUE TITLE
lm() crashes with 1-dimensional regressor array

### ISSUE THREAD

**Issue by BenjaminBorn** [JuliaStats/GLM.jl#230]
The following works
```
using GLM

y   = randn(100)
x_1 = randn(100)
x_0 = ones(size(x_1))

x = [x_0 x_1]
ols_output = lm(x, y)
```
as `x` is a 2-dimensional `Array{Float64,2}`. 

But let's say I want to exclude the constant so that `x = x_1`, i.e. a 1-dimensional `Array{Float64,1}`. Then `ols_no_const = lm(x, y)` yields
```
MethodError: no method matching fit(::Type{GLM.LinearModel}, ::Array{Float64,1}, ::Array{Float64,1}, ::Bool)
Closest candidates are:
  fit(::Type{StatsBase.Histogram}, ::Any...; kwargs...) at /Users/bborn/.julia/v0.6/StatsBase/src/hist.jl:340
  fit(::StatsBase.StatisticalModel, ::Any...) at /Users/bborn/.julia/v0.6/StatsBase/src/statmodels.jl:151
  fit(::Type{D<:Distributions.Distribution}, ::Any...) where D<:Distributions.Distribution at /Users/bborn/.julia/v0.6/Distributions/src/genericfit.jl:34
  ...

Stacktrace:
 [1] lm(::Array{Float64,1}, ::Array{Float64,1}) at /Users/bborn/.julia/v0.6/GLM/src/lm.jl:150
```

I don't see why the case of one regressor should not be allowed.

**Comment by andreasnoack** [comment]
> I don't see why the case of one regressor should not be allowed.

It is allowed, it just has to be a `Matrix`, i.e. initialize with `x_1 = randn(100,1)`. Allowing `X` to be a `Vector` is possible but would complicate the code for no obvious benefit.

**Comment by BenjaminBorn** [comment]
Thanks for your quick reply Andreas.

If I initialize with `x_1=randn(100, 1)` and run `lm(x_1, y)` I get
```
MethodError: no method matching fit(::Type{GLM.LinearModel}, ::Array{Float64,2}, ::Array{Float64,2}, ::Bool)
Closest candidates are:
  fit(::Type{StatsBase.Histogram}, ::Any...; kwargs...) at /Users/bborn/.julia/v0.6/StatsBase/src/hist.jl:340
  fit(::StatsBase.StatisticalModel, ::Any...) at /Users/bborn/.julia/v0.6/StatsBase/src/statmodels.jl:151
  fit(::Type{D<:Distributions.Distribution}, ::Any...) where D<:Distributions.Distribution at /Users/bborn/.julia/v0.6/Distributions/src/genericfit.jl:34
  ...

Stacktrace:
 [1] lm(::Array{Float64,2}, ::Array{Float64,2}) at /Users/bborn/.julia/v0.6/GLM/src/lm.jl:150
```

**Comment by BenjaminBorn** [comment]
Sorry, ignore my last comment. It works. I accidentally also had `y` as a 2-dimensional array in the last case.

**Comment by BenjaminBorn** [comment]
Maybe one last comment in favour of allowing for a  regressor vector. If I have the regressor matrix `x` as above, then `lm(x[:, 2], y)` won't work as `x[:, 1]` is again a vector.

**Comment by andreasnoack** [comment]
That is a general concern when slicing and the general solution is to slice with a one element range, i.e. `lm(x[:,2:2], y)`
