### ISSUE TITLE
Version to support StatsModels 0.2.4?

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/GLM.jl#233]
Will the next version of `GLM` allow for `StatsModels v0.2.4`?  Right now I am caught in a dependency trap for the [`MixedModels`](https://github.com/dmbates/MixedModels.jl) package if I wish to allow for `StatsModels v0.2.4`

**Comment by kleinschmidt** [comment]
The only change that needs to be made AFAIK is to change one of the tests that explicitly calls `Formula` to make a one-sided formula (#222). Have you come across other issues?

**Comment by dmbates** [comment]
I haven't encountered other issues.  To me it is just a staging question - I need a version of `GLM` that allows `StatsModels v0.2.4` before I can release a `MixedModels` version.

**Comment by andreasnoack** [comment]
Fixed by #222

**Comment by kleinschmidt** [comment]
Should tag a new release now?

**Comment by andreasnoack** [comment]
We can do it now or when the doc reorganization has been merged. I'm fine with both.
