### ISSUE TITLE
confint with different probability

### ISSUE THREAD

**Issue by DominiqueMakowski** [JuliaStats/GLM.jl#241]
By running `?confint` it seems that there is no `prob` argument that could be used to change the default probability at which confint is computed. Is this in the plans?

**Comment by nalimilan** [comment]
The functionality is there:
https://github.com/JuliaStats/GLM.jl/blob/fc5baf3c9dec51326e6f82d4183e888f92fedca8/src/glmfit.jl#L170

We only need to improve the docstring. See https://github.com/JuliaStats/StatsBase.jl/pull/406.

**Comment by DominiqueMakowski** [comment]
@nalimilan Great!
