### ISSUE TITLE
Release for Julia 1.0

### ISSUE THREAD

**Issue by Nosferican** [JuliaStats/GLM.jl#244]
Leaving this issue to track the progress.

**Comment by andreasnoack** [comment]
Let's just track that in #242

**Comment by Nosferican** [comment]
Is kinda nice to leave an issue and refer to the PR on it... would have saved me a few hours. :(
I made [this](https://github.com/Nosferican/GLM.jl/commit/4860b80adf2d14c0b48ce19638ceeadff2d65d76) before finding out about the open PR... That one is done so might be nice to just copy whatever y'all need or compare for accuracy.
