### ISSUE TITLE
Error when installing GLM v0.11.0 in Julia 1.0

### ISSUE THREAD

**Issue by nhavt** [JuliaStats/GLM.jl#245]
Hi all, when installing GLM v0.11.0 in Julia 1.0, I obtained an error "LoadError: UndefVarError: LinAlg not defined". This error occurred as the command "using Base.LinAlg.LAPACK" had been called in GML.jl. My guess is that in Julia 1.0 the lib"Base.LinAlg.LAPACK" does not exist. Instead, we have to use the lib "LinearAlgebra.BLAS" (see at https://docs.julialang.org/en/stable/stdlib/LinearAlgebra/#BLAS-Functions-1). Could you please have a look at it? Thanks in advance!

**Comment by andreasnoack** [comment]
Julia 1.0 is not yet supported. It's close though. See https://github.com/JuliaStats/GLM.jl/pull/242.

**Comment by nhavt** [comment]
Ok, thanks for your quick response!
