### ISSUE TITLE
following README.MD failed

### ISSUE THREAD

**Issue by omorr** [JuliaStats/GLM.jl#25]
I just tried to test GLM following the README.MD but it simply does not work whatever I try (*different packages using in different order* ), lm() simply does not work
+++++++++++++++++++
julia> using DataFrames, Distributions, GLM
Warning: New definition refModResp not defined
at C:\Users\omorjan\AppData\Roaming\julia\packages\GLM\src\GLM.jl:18

julia> 
(DataArray{T,N},Union(BitArray{1},Array{Bool,1})) is ambiguous with ref(DataArray{T<:Number,N},Union(BitArray{1},Ranges{T},Array{T,1})) at C:\Users\omorjan\AppData\Roaming\julia\packages\DataFrames\src\dataarray.jl:339.
         Make sure ref(DataArray{T<:Number,N},Union(BitArray{1},Array{Bool,1})) is defined first.

julia> using RDatasets, GLM
invalid redefinition of constant GlmResp
at C:\Users\omorjan\AppData\Roaming\julia\packages\GLM\src\GLM.jl:18

julia> form = data("datasets", "Formaldehyde")
6x3 DataFrame:
          carb optden
[1,]    1  0.1  0.086
[2,]    2  0.3  0.269
[3,]    3  0.5  0.446
[4,]    4  0.6  0.538
[5,]    5  0.7  0.626
[6,]    6  0.9  0.782

julia> fm1 = lm(:(optden ~ carb), form)
lm not defined
++++++++++++++++++++++

**Comment by pkofod** [comment]
I figure this can be closed as it is about a very old version of julia and GLM, and since Julia Studio is no longer in active development.
