### ISSUE TITLE
GLM.lm fails when X is a vector

### ISSUE THREAD

**Issue by pdeffebach** [JuliaStats/GLM.jl#254]
It would be nice to be able to do 

```
x = rand(20)
y = rand(20)
lm(x, y)
```

This fails because `x` is a vector, and not a matrix. 

This is useful only because users might expect it to be the case. 

```
fit(model, X::AbstractVector, y) = fit(model, reshape(X, :, 1), y) # now X is a matrix
```

**Comment by andreasnoack** [comment]
Is this really needed? I'd rather avoid this extra method. Requiring that the design matrix is a `Matrix` doesn't seem that surprising and regressions without a constant term are pretty rare.

**Comment by pdeffebach** [comment]
Also remember that you can always do `X[:,:]` to get a 2-d array from a 1-d array. So you don't even need to bother with an `reshape` command.

**Comment by ararslan** [comment]
That's less efficient though as it makes a copy of `X`. `reshape` shares memory with `X`.
