### ISSUE TITLE
`lm` doesn't support wts

### ISSUE THREAD

**Issue by pdeffebach** [JuliaStats/GLM.jl#258]
```
julia> using DataFrames, GLM

julia> df = DataFrame(y = randn(100), x = randn(100), w = rand(100) .+ 1);

julia> m = lm(@formula(y ~ x), df)
StatsModels.DataFrameRegressionModel{LinearModel{LmResp{Array{Float64,1}},DensePredChol{Float64,LinearAlgebra.Cholesky{Float64,Array{Float64,2}}}},Array{Float64,2}}

Formula: y ~ 1 + x

Coefficients:
               Estimate Std.Error   t value Pr(>|t|)
(Intercept)   -0.108285 0.0909041  -1.19119   0.2365
x            -0.0154871 0.0855186 -0.181096   0.8567


julia> m = lm(@formula(y ~ x), df, wts = df.w)
ERROR: function lm does not accept keyword arguments
Stacktrace:
 [1] kwfunc(::Any) at .\boot.jl:321
 [2] top-level scope at none:0
```

Is there any way to add weights to `lm`. Or is the recommendation to use `glm` for any more complex regression? 

I would have expected `lm(f, df; kwargs...)` to simply be a wrapper for `glm(f, df, Normal(), IdentityLink(); kwargs...)` but that isn't the case. Is there a reason for this?

**Comment by nalimilan** [comment]
> I would have expected `lm(f, df; kwargs...)` to simply be a wrapper for `glm(f, df, Normal(), IdentityLink(); kwargs...)` but that isn't the case. Is there a reason for this?

Yes, linear regression can be fitted more efficiently than GLMs.

I guess nobody has added support for weights, but it should be relatively easy to do for frequency weights.

**Comment by pdeffebach** [comment]
It looks like all of the model response objects allow for weights. But it's a bit beyond me at this point to make a PR. 

Bump for weights to be in the model object as well though.

**Comment by nalimilan** [comment]
Indeed. Maybe all that's needed is to fix `fit` to accept weights an pass them to `LmResp` then.
