### ISSUE TITLE
Linear models could be faster.

### ISSUE THREAD

**Issue by skanskan** [JuliaStats/GLM.jl#267]
Hello.

I've been looking for fast packages to fit a linear regression model and found that GLM is slow.
For example with this toy example:
```
using DataFrames, GLM
N=3000
x1 = repeat(1:N, outer=N)
x2 = repeat(1:N, inner=N)
x3 = sqrt.(1:N^2)
x1x2 = x1 .* x2
y = 1 .- 2*x1 + 3*x2 + 0.5*x1x2 + rand(N^2) + x3.*rand(N^2)
data = DataFrame(x1=x1, x2=x2, x3=x3, x1x2=x1x2, y=y)
dat2 = hcat(ones(length(x1)), x1, x2, x1x2, x3)
```

If you calculate the coefficients with:
`@time (dat2' * dat2) \ (dat2' * y)`
you get the same output than GLM
`lm(@formula(y ~ x1+x2+x3+x1x2), data)`
but much faster because the size of the matrix to be inverted is much reduced.
I know GLM also calculates more things but the difference is too big.
Maybe it should change the way it does the calculation.

Some people here https://discourse.julialang.org/t/glm-is-slow-on-large-datasets-using-onlinestats-for-regressions-mixedmodels/17695/10   told me  I can calculate the coefficients with
`@time dat2 \ y    #usa QR` because is more accurate, but the result doesn't match up with GLM's and it's slower because the inversion is done on the whole initial matrix.

**Comment by andreasnoack** [comment]
Please ask questions on discourse.

**Comment by skanskan** [comment]
But it's not a question, it's a request to add this faster method.
I did also opened a thread at discourse before.

**Comment by nalimilan** [comment]
> I know GLM also calculates more things but the difference is too big.
> Maybe it should change the way it does the calculation.

Unless you explain precisely how to extract the same information as GLM does with the method you mention, this issue is a question, not a proposal. The Discourse thread shows that these things are more complex than that.
