### ISSUE TITLE
Initialization of v in the deviance function

### ISSUE THREAD

**Issue by leejm516** [JuliaStats/GLM.jl#268]
I have discussed this topic with other people in Discourse.
[https://discourse.julialang.org/t/purpose-of-zero-in-a-function/18095]

In this function, v is initialized by

`v = zero(eltype(y)) + zero(eltype(y)) * zero(eltype(wts))`

If it is needed for type inference (and therefore improving performance?), I do not understand why `zero(eltype(y))` occurs twice and where `zero(eltype(mu))` is, which is used in the downstream loop. As a learner of Julia, I just wonder whether it is mistake or not.

**Comment by nalimilan** [comment]
That's just us being overly zealous. To be 100% sure the type won't change during computations, you need in theory to call exactly the same functions as you will do in the loop below. `eltype(y)` occurs twice because in theory the addition could change the type. In practice it's unlikely to matter.
