### ISSUE TITLE
Confidence Interval for certain Contrast and model residual

### ISSUE THREAD

**Issue by PharmCat** [JuliaStats/GLM.jl#278]
I have a model:

`ols = lm(@formula(LnVar ~ Seq+Per+Trt+Subj), df)`

I try to get confidence interval for Trt contrast and model residual. How to obtain it?

In R you just do `confint(lmobj, c("Trt"), level=0.9)`  and `summary(lmobj )$sigma^2 `

And I can not find any working example. And model residual i can not find at all.  Is any question board anywhere?

**Comment by ararslan** [comment]
> Is any question board anywhere?

Yes indeed! The official Q&A and discussion forum for Julia is at https://discourse.julialang.org. That's the best place to get answers to questions about usage. We try to keep the GitHub issue tracker for bug reports and feature requests.

**Comment by PharmCat** [comment]
Ok. I'll try to find there.
