### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by PharmCat** [JuliaStats/GLM.jl#279]
In common use is critical to have good error handling of called methods and functions. In some cases is totally ununderstandable where are you wrong and what to do with it.

**Comment by ararslan** [comment]
Can you give an example of a situation you've encountered with a particularly cryptic error or similar?

**Comment by PharmCat** [comment]
For example when i call predict() function in some situations i have ERROR: StackOverflowError:
and it difficult to understand where error is

also in predict() i cat get error: ERROR: DimensionMismatch("first array has length 2 which does not match the length of the second, 5.")
this error is not handled and my logical mistake lead to program error, in user oriented functions it is very important to have good check for this kind of errors
and in predict():
ERROR: MethodError: no method matching predict
it is not easy to understand what kind of matrix expected. Here is no any association with R, SPSS or SAS and this error explain nothing

**Comment by nalimilan** [comment]
Can you post reproducible examples?

**Comment by palday** [comment]
With reproducible examples, this issue can be re-opened but I'm not sure how to provide better error messages without reproducible examples or at least more error output.
