### ISSUE TITLE
Dispersion docstring

### ISSUE THREAD

**Issue by tlienart** [JuliaStats/GLM.jl#283]
The docstring currently specifies

```
Return the estimated dispersion (or scale) parameter for a model's distribution,
generally written σ² for linear models and ϕ for generalized linear models.
It is, by definition, equal to 1 for the Bernoulli, Binomial, and Poisson families.
```

I may have confused myself but shouldn't it be just `σ` for linear models?

**Comment by nalimilan** [comment]
Good catch. AFAICT σ is returned by default since `sqr=false`. See https://github.com/JuliaStats/GLM.jl/pull/284.
