### ISSUE TITLE
Distribution examples in the docs?

### ISSUE THREAD

**Issue by ianshmean** [JuliaStats/GLM.jl#289]
I thought it might be helpful to include default examples beside the list of typical distributions in the docs [here](http://juliastats.github.io/GLM.jl/dev/manual). Something like this:
![image](https://user-images.githubusercontent.com/1694067/53687422-7396c380-3d02-11e9-8b65-8fe879a0cb57.png)

```julia
using Distributions, PyPlot
figure(figsize=(7,5))
dfxs = [Bernoulli(),Binomial(),Gamma(),InverseGaussian(),NegativeBinomial(),Normal(),Poisson()]
dnames = ["Bernoulli","Binomial","Gamma","InverseGaussian","NegativeBinomial","Normal","Poisson"]
for i in 1:length(dfxs)
    subplot(7,1,i); subplots_adjust(hspace=0)
    PyPlot.plt[:hist](rand(dfxs[i], 100000),-7.5:0.1:7.5,align="left",label="x");xticks(-8:8)
    ax= gca()
    ax[:yaxis][:set_visible](false);ax[:spines]["left"][:set_visible](false);ax[:spines]["right"][:set_visible](false);ax[:spines]["top"][:set_visible](false)
    i !== length(dfxs) && ax[:xaxis][:set_visible](false);annotate(dnames[i],xy=[0,0.5],xycoords="axes fraction",ha="right",va="center")
end
```

**Comment by nalimilan** [comment]
Thanks for the suggestion, but wouldn't this be more appropriate for Distributions.jl? I don't think people are likely to choose the distribution of their models based on plots: usually the choice is directly determined by the kind of data (binary, count...) or by the literature rather than by how it looks.

**Comment by ianshmean** [comment]
Fair point. It’s probably overly simplistic too.
