### ISSUE TITLE
Thoughts about improving on R WRT contrasts

### ISSUE THREAD

**Issue by nalimilan** [JuliaStats/GLM.jl#29]
Not sure this is the right place nor whether this may be of any use to you, but anyway...

I feel it's great that you write a GLM package from scratch while knowing very well the existing R implementation so that you take the best of it and improve it where needed. With that idea in mind, I'd like to share two points that I consider limits of the current handling of contrasts in R.

1) In R, to set the reference level when using treatment contrasts, you need to change the order of levels (since the first is used). This is often cumbersome when you have a natural ordering of levels, and yet you would like to take a category in the center of the scale. Once you have made that category the first one, you cannot use the variable anymore e.g. to do a barplot, a table or anything, since the order is not correct. Duplicating a variable just for this detail is not ideal (memory use, potential mistakes when updating one and not the other...).

So IMHO it would be nice to be able to save the reference level separately from the order of levels.

2) In R, redundant contrast levels are not included in the model: the reference category (for treatment contrasts) or the last category (for sum contrasts) are lost. This means that regression tables, be they on screen or for output to a document (e.g. using Sweave), cannot show these values while there are usually needed for publication-grade tables, and anyway very useful to the researcher.

Thus, it would be nice if the models could somewhat remember these contrast levels, and allow retrieving them via a function similar to coef(). I would even hold that they should be printed by the default show() method.

I realize that for sum contrasts things are a little more complex since the last contrast level is not equal to 0, but to the sum of all other coefficients. So this needs a more generic handling, which could likely be part of a contrast object.

**Comment by andreasnoack** [comment]
@nalimilan Is it useful to keep this one open?

**Comment by kleinschmidt** [comment]
If so, it should be moved to https://github.com/JuliaStats/StatsModels.jl

**Comment by nalimilan** [comment]
I guess we can close this, will need to discuss more precisely in StatsModels.jl.
