### ISSUE TITLE
how to put start values into glm estimation

### ISSUE THREAD

**Issue by valeraiibaidin** [JuliaStats/GLM.jl#296]
Would you help, how to initialize start value for glm estimation?

There is information in the documentation. I have a little experience on how to use it.
```

fit(GeneralizedLinearModel, X, y, d, [l = canonicallink(d)]; <keyword arguments>)
Keyword Arguments
...........
start::AbstractVector=nothing: Starting values for beta. Should have the  Should have the
same length as the number of columns in the model matrix.


```
thank you.

**Comment by nalimilan** [comment]
Please use [the Discourse forum](http://discourse.julialang.org/) for questions, and keep GitHub for bug reports. Thanks!

Also maybe have a look at https://github.com/JuliaStats/GLM.jl/issues/297.
