### ISSUE TITLE
StatsModels not accessible on Github

### ISSUE THREAD

**Issue by xtk923** [JuliaStats/GLM.jl#310]
Trying to install GLM returns 404 for StatsModels.

**Comment by lcwright1964** [comment]
Ditto. Moreover, I was asked to enter my GitHub credentials, and THEN I got the 404 error. Struck me as weird. I have always been able to download and install packages in the REPL even before I got a GitHub acct.

**Comment by andreasnoack** [comment]
Please see https://discourse.julialang.org/t/juliastats-statsmodels-package-missing/23880
