### ISSUE TITLE
Full API should be in online documentation

### ISSUE THREAD

**Issue by cmcaine** [JuliaStats/GLM.jl#326]
The docstrings for e.g. `ftest` are not present in the generated
documentation but are quite useful. I think the full API should be in
the generated docs.

**Comment by nalimilan** [comment]
Sure. Would you add them to the relevant files?

**Comment by cmcaine** [comment]
There's a bunch of stuff missing. How do you feel about `@autodocs`? https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@autodocs-block-1
