### ISSUE TITLE
Mean Squared Error

### ISSUE THREAD

**Issue by Jo-Fleck** [JuliaStats/GLM.jl#344]
Is there a way to obtain the mean squared error (mse) from a linear regression from the fitted model (as `coef` and `stderror`)? I have tried `deviance' but it doesn't give me the same result as computing the mse 'by hand'. Thanks!

**Comment by nalimilan** [comment]
Have you tried `deviance(mod)/dof_residual(mod)`?

**Comment by Jo-Fleck** [comment]
@nalimilan Thanks! That's it.
