### ISSUE TITLE
lm doesn't work for complex numbers

### ISSUE THREAD

**Issue by smackesey** [JuliaStats/GLM.jl#36]
Shouldn't it?  This is useful in signal processing.  Right now I am just solving my complex regression problems with `pinv(X'X)*X'*Y`, but it doesn't produce the nice output of `lm` and it is not scalable to problems with tons of predictors.

**Comment by andreasnoack** [comment]
I don't think there is an obvious way to extend this package to complex numbers. Most treatments of these models assume real data and I'm not sure how the inference would look like in the complex case. The estimators would be complex so the how should the output look like? It seems to me that the variance of each coordinate of the estimator would be a matrix.

**Comment by Losses** [comment]
@andreasnoack It's a really important feature for signal processing, details could be found here: https://stats.stackexchange.com/questions/66088/analysis-with-complex-data-anything-different

please give it a consideration...

**Comment by andreasnoack** [comment]
I still think it's beyond the scope of this package. If somebody could show that it could be implemented without complicating the existing code, I'd be fine with reconsidering this.

**Comment by Losses** [comment]
@andreasnoack I..... I will have a try with my weak math and programming knowledge...... anyway........
