### ISSUE TITLE
Question: Does this package have support for generalized least squares

### ISSUE THREAD

**Issue by spencerlyon2** [JuliaStats/GLM.jl#37]
I need to do generalized least squares and would like to use this package. 

Is there an existing way to specify the variance of the residual, so as to do weighted least squares?

**Comment by floswald** [comment]
this works:

```julia
data=DataFrame(X=[1,2,3],Y=[2,4,7],wts = rand(3))
OLS = glm(Y~X,data,Normal(),IdentityLink(),wts=data[:wts].data)
```

can this be closed?

**Comment by nalimilan** [comment]
Let's close this. There's a discussion in https://github.com/JuliaStats/GLM.jl/issues/124 about weights.
