### ISSUE TITLE
Cooks distance

### ISSUE THREAD

**Issue by ericqu** [JuliaStats/GLM.jl#414]
I would like to use Cook's distance.
And I noted that there is already a PR for this here: https://github.com/JuliaStats/GLM.jl/pull/368 .
Is it because there is no test for the function that the PR is stuck?
Should I write a/some tests to unstuck the PR? If so, is there some guideline on how to do so ?

**Comment by ararslan** [comment]
Hi @ericqu, thanks for your willingness to contribute! If you'd like to add tests, you could look at the existing tests for this package in the test directory and mimic the style of how things are tested. You'd just want to make sure that the values computed from the function in Julia are approximately equal to those computed from another reputable source, e.g. R. If you come up with some tests, you can leave them in a comment in #368 and a maintainer can apply them, or you can make a PR that includes the changes from #368.

**Comment by ericqu** [comment]
Hi @ararslan, I thought that it would be a learning opportunity to make PR and test and I thought of doing a PR myself.
Unfortunately, I run into some troubles (see PR #415 ) not so much about the function itself but how to function integrate within GLM and StatsModels which I did not anticipate. I would be grateful if you could have a quick look into it and give me some pointer to progress further and eventually close the issue.
