### ISSUE TITLE
License terms incomplete?

### ISSUE THREAD

**Issue by rcurtin** [JuliaStats/GLM.jl#441]
Hi there!  Thank you for this excellent package.  I had a question about licensing.

The license in the repository is the MIT license, but due to GLM's dependency on Distributions, which in turn depends on StatsFuns, there is a dependency on the GPL-ed Rmath library via [Rmath.jl](https://github.com/JuliaStats/Rmath.jl).  But, that isn't noted here.  Hence my surprise when I realized that building and distributing something on top of GLM.jl would in turn mean that whatever I distributed would need to be under the terms of the GPL. :)

Is it possible to perhaps remove the Rmath dependency and use a different dependency for what that package is currently being used for?  (Please note, I am ignorant of whether that is easy and will take five minutes, or is a huge amount of work... just throwing it out there. :))  Or, at least maybe it is worth updating the license here to match something a little more like [FFTW.jl's](https://github.com/JuliaMath/FFTW.jl#license), or use a [THIRDPARTY.md file](https://github.com/JuliaLang/julia/blob/master/THIRDPARTY.md)?

In any case, this presents a bit of a blocker for my usage of GLM.jl, and so I'd really appreciate any input towards what a path to resolution could be.

Thanks!

**Comment by rcurtin** [comment]
(see also https://github.com/JuliaStats/Rmath.jl/issues/75)

**Comment by nalimilan** [comment]
As noted at https://github.com/JuliaStats/Rmath.jl/issues/75#issuecomment-912984117:
> I'd say it would be reasonable to make PRs to packages that depend on Rmath to add a THIRDPARTY.md file and a reference to it in LICENSE.md. Though of course it will be very hard to be exhaustive given that these are quite fundamental packages that are used indirectly by many packages (and new ones are added all the time).

**Comment by rcurtin** [comment]
See #447. :+1:
