### ISSUE TITLE
r2 for GLM

### ISSUE THREAD

**Issue by mousum-github** [JuliaStats/GLM.jl#475]
The documentation says that the `r2` function computes `R²` of a linear model or pseudo-R² of a generalized linear model.
But if we call `r2` with any `glm` fitted model, it throws an error. I have come across a lot of debates on `r2`, `nulldeviance` etc for `GLM` in the forum.
It would be better if we remove the `pseudo-R²` part from the documentation until the same is implemented for `GLM`.

**Comment by nalimilan** [comment]
Good catch. See https://github.com/JuliaStats/GLM.jl/pull/477.

**Comment by nalimilan** [comment]
Fixed by https://github.com/JuliaStats/GLM.jl/pull/479.
