### ISSUE TITLE
Prediction with confidence intervals not yet implemented for weighted regression

### ISSUE THREAD

**Issue by jariji** [JuliaStats/GLM.jl#495]
I just hit this error.

https://github.com/JuliaStats/GLM.jl/blob/f149f2bee3336914dfcbbe033474add270567c63/src/lm.jl#L267

One [Discourse answer](https://discourse.julialang.org/t/weighted-linear-regression-with-confidence-interval/60610/4) suggests using `glm(f,d,Normal())` instead of `lm` as a workaround. I'm not sure if that's equivalent.

**Comment by nalimilan** [comment]
These will give the same predicted values, but  I'm not sure they would give the same confidence intervals (T distribution vs normal distribution). Anyway the result will be statistically sound in both cases at least.
