### ISSUE TITLE
infinite uninterruptible hang on one illegal input to ftest

### ISSUE THREAD

**Issue by xgdgsc** [JuliaStats/GLM.jl#538]
[ftesthang.csv](https://github.com/JuliaStats/GLM.jl/files/11705218/ftesthang.csv)
```jl
using CSV
using GLM
using DataFrames
regData = CSV.read("ftesthang.csv", DataFrame)
ols = lm(@formula(Y ~ X1 + X2 + X3 + X4 + X5 + X6 + 1), regData)
oCoefs = coef(ols)
ftestRes = ftest(ols.model)
```
With this illegal input. `ftest` hangs in an infinite uninterruptible way. Is it possible to throw an error instead?

**Comment by ararslan** [comment]
Looks like the continued fraction implementation of the incomplete beta function in SpecialFunctions gets stuck in an infinite loop because there's no check that the input is finite.

**Comment by andreasnoack** [comment]
Okay! That's a pretty degenerate case. This is now fixed upstream.
