### ISSUE TITLE
Why are there two different domains for documentation? 

### ISSUE THREAD

**Issue by LLTeixeira** [JuliaStats/GLM.jl#541]
The first documentation to show up on Google is:
https://juliastats.org/GLM.jl/v1.7/

However as you can see it is outdated as the most recent is:
https://docs.juliahub.com/GLM/6OREG/1.8.3/

That is quite confusing as the docs with the most visibility are not up to date and they both look the same so you might not even notice you're supposed to be on another site.

**Comment by ararslan** [comment]
I'm not sure how JuliaHub populates its documentation but juliastats.org uses what's on the gh-pages branch of this repository which is populated by the Documenter CI workflow. It appears the documentation workflow wasn't updated to allow building on pushes to branches other than master, and the most recent release was made from the v1 branch. That should be a simple fix.

**Comment by ParadaCarleton** [comment]
Fixed by #542
