### ISSUE TITLE
Add additional methods

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/GLM.jl#7]
- [ ] add1.lm*
- [ ] alias.lm*
- [x] anova.lm* -> `ftest` (#182)
- [ ] case.names.lm*
- [x] confint.lm*
- [ ] cooks.distance.lm*
- [x] deviance.lm*
- [ ] dfbeta.lm*
- [ ] dfbetas.lm*
- [ ] drop1.lm*
- [ ] dummy.coef.lm*
- [ ] effects.lm*
- [x] extractAIC.lm\* -> `aic`, `bic`
- [x] family.lm*
- [ ] formula.lm*
- [ ] hatvalues.lm*
- [ ] influence.lm*
- [ ] kappa.lm*
- [ ] labels.lm*
- [x] logLik.lm\* -> `loglikelihood`
- [x] model.frame.lm*
- [x] model.matrix.lm*
- [x] nobs.lm*
- [ ] plot.lm*
- [ ] predict.lm*
- [ ] print.lm*
- [ ] proj.lm*
- [ ] qr.lm*
- [x] residuals.lm*
- [ ] rstandard.lm*
- [ ] rstudent.lm*
- [ ] simulate.lm*
- [ ] summary.lm*
- [ ] variable.names.lm*
- [x] vcov.lm*

**Comment by nalimilan** [comment]
See https://github.com/JuliaStats/StatsBase.jl/issues/280 about improving the consistency of our modeling API

**Comment by Nosferican** [comment]
See [JuliaStats/StatsBase.jl PR#355](https://github.com/JuliaStats/StatsBase.jl/pull/355). It includes a few such as `leverage`. For `rstandard` and `rstudent`, those could be added to `residuals` with keyword arguments. We could add also add `formula(::StatisticalModel)`.

**Comment by nico202** [comment]
Any way leverage and cooks distance will be added?

**Comment by andreasnoack** [comment]
I don't think this issue is needed anymore. Some of these methods belong in other packages and some might not be needed at all. We can file individual issues for missing functionality.
