### ISSUE TITLE
Functions to evaluate fit

### ISSUE THREAD

**Issue by johansigfrids** [JuliaStats/GLM.jl#74]
I can't seem to find any functions for evaluating the fit for a linear model. Does GLM have ways to get things like R^2, adjusted R^2, sigma, AIC, BIC?

**Comment by JonathanAnderson** [comment]
i've been looking for this too.

when i need r2 i use:

```
R²(lm) = 1-norm(lm.model.rr.y-predict(lm))/norm(lm.model.rr.y)
```

**Comment by gragusa** [comment]
skype: gasugar

Giuseppe Ragusa

On Thu, Oct 29, 2015 at 2:53 PM, Jonathan Anderson <notifications@github.com

**Comment by gragusa** [comment]
Sorry for the noise. I mistakenly replied to this....

Giuseppe Ragusa

**Comment by nalimilan** [comment]
I've made two PRs implementing the necessary functions: https://github.com/JuliaStats/StatsBase.jl/pull/146 and https://github.com/JuliaStats/GLM.jl/pull/115. Please comment/review!

**Comment by diegozea** [comment]
I was also looking for R² in GLM...
