### ISSUE TITLE
Preferred formula API?

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/GLM.jl#8]
I've set up things so that the user can do:

```
lm("y ~ x", df)
```

I feel like this is less intimidating to new users. Of course, it does so by separating users from the work being done under the hood. I'd like to know whether others think this is a good thing. Any thoughts @dmbates, @andreasnoackjensen, @HarlanH, @doobwa or @tshort?

**Comment by andreasnoack** [comment]
Closing since formulas are part of `DataFrames`

**Comment by ararslan** [comment]
...and will soon be part of StatsModels.jl. 🙂
